# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ffvIRKb1-r_B32fopYQxcctEd3KuHfp5

# HW4 - Friends of Friends
### Quentin Phillips
### DATA 440-02
### 11/1/23

# Q1: Stats
First I added the user to the data as having 98 friends in order to compare the user to the rest of the data.

Mean: I sorted the values in a column by friends and then calculated the mean to be 538.13
Standard Dev: I used the STDEV function in excel to find the standard deviation at 538.53
Median: The median value was simple to find after sorting. The median of the data set is 395

# Q2: Friendship Paradox

The friendship paradox does hold for this data. The mean and median are both significantly higher than the users data.

Here is the graph of the data points with the user highlighted in orange:

(https://github.com/QuentinPhil/DATA44002/blob/main/HW4/Friends%20by%20Friend%20Count.png)
"""

